#    Author: Alex Savatieiev (a.savex@gmail.com)
#    November 2025
try:
    # Generated by setuptools-scm from the git tag at build/install time
    from dotclient._version import __version__
except ImportError:
    # Running from a source tree that was never built or installed
    __version__ = "0+unknown"
